# Generated by Django 4.0.3 on 2022-12-07 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilevo',
            name='vin',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='service_rest.technician'),
        ),
        migrations.AlterField(
            model_name='service',
            name='time',
            field=models.TimeField(),
        ),
    ]
