# Generated by Django 4.0.3 on 2022-12-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_rest', '0002_automobile_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='finished',
            field=models.CharField(default='UNSOLD', max_length=100),
        ),
    ]
